server:
  port: 8011

spring:
  application:
    name: goods-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/changgou_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: innosen

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8010/eureka/
    register-with-eureka: true
    fetch-registry: false

mybatis:
  type-aliases-package: com.tabwu.changgou.pojo

logging:
  level:
    com.example.springboot03: debug