server:
  port: 8011

spring:
  application:
    name: goods-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.193.24:3306/changgou_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1/8010/eureka
    register-with-eureka: true
    fetch-registry: false

mybatis:
  type-aliases-package: com.tabwu.changgou.pojo