server:
  port: 9001

spring:
  application:
    name: gateway-web
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations: #跨域请求配置
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - DELETE
              - PUT
              - POST

      routes:
          - id: file-service-route
            uri: lb://file-service
            predicates:
              - Path=/file/**
            filters:
              - StripPrefix=1

          - id: goods-service-route
            uri: lb://goods-service
            predicates:
              - Path=/goods/**
            filters:
              - StripPrefix=1
#              - name: RequestRateLimiter
#                args:
#                  key-resolver: "#{@ipLeyResolver}"
#                  redis-rate-limiter.replenishRate: 1
#                  redis-rate-limiter.burstCapacity: 2

          - id: search-service-route
            uri: lb://search-service
            predicates:
              - Path=/search/**
            filters:
              - StripPrefix=1
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@ipLeyResolver}"
#                    redis-rate-limiter.replenishRate: 1
#                    redis-rate-limiter.burstCapacity: 2

          - id: user-service-route
            uri: lb://user-service
            predicates:
              - Path=/api/**
            filters:
              - StripPrefix=1
#              - name: RequestRateLimiter
#                args:
#                  key-resolver: "#{@ipLeyResolver}"
#                  redis-rate-limiter.replenishRate: 1
#                  redis-rate-limiter.burstCapacity: 2




eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8010/eureka
    register-with-eureka: true
    fetch-registry: true