server:
  port: 8012

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8010/eureka/
    register-with-eureka: true
    fetch-registry: false

